# Generated by Django 4.1.3 on 2022-11-19 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.SlugField(unique=True)),
                ('fancy_name', models.CharField(default='verbose name of a show', max_length=200)),
                ('fancy_description', models.CharField(default='A description of a JB Show!', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('ep_title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('url_link', models.URLField()),
                ('audio_link', models.URLField()),
                ('vtt_link', models.FileField(upload_to='media/vtt/')),
                ('transcript_link', models.FileField(upload_to='media/vtt/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jbcontent.show')),
            ],
        ),
    ]
