# Generated by Django 4.1.3 on 2022-11-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbcontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='fancy_description',
            field=models.CharField(default='A description of a JB Show!', max_length=250),
        ),
        migrations.AlterField(
            model_name='show',
            name='fancy_name',
            field=models.CharField(default='verbose name of a show', max_length=200),
        ),
    ]
