# Generated by Django 4.1.3 on 2022-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='transcript',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
